name=MioMPU6050
version=1.0.0
author=Tuo Nome
maintainer=Tuo Nome
sentence=Libreria personale per MPU6050.
paragraph=Gestione base del MPU6050 via I2C: inizializzazione, lettura accelerometro, giroscopio e temperatura.
category=Sensors
url=https://github.com/tuonome/MioMPU6050
architectures=*
depends=Wire